microsoft/ml-wrappers

- python/README.md
- python/ml_wrappers/__init__.py
- python/ml_wrappers/common/__init__.py
- python/ml_wrappers/common/constants.py
- python/ml_wrappers/dataset/__init__.py
- python/ml_wrappers/dataset/dataset_wrapper.py
- python/ml_wrappers/model/__init__.py
- python/ml_wrappers/model/model_wrapper.py
- python/ml_wrappers/version.py
- python/setup.cfg
- python/setup.py
Initial commit of the ML wrappers repository!
The Machine Learning Wrappers SDK provides a unified wrapper for various ML frameworks - to have one uniform scikit-learn format predict and predict_proba functions.
Highlights of the package include:
- A dataset wrapper to handle scipy sparse, pandas and numpy datasets in a uniform manner.
- A model wrapper to handle models from various frameworks uniformly, including scikit-learn, tensorflow, pytorch, lightgbm and xgboost
Please see the github website for the documentation and sample notebooks:
https://github.com/microsoft/ml-wrappers
> initial commit

- python/ml_wrappers/model/__init__.py
fix init file to include _wrap_model, wrap_model and WrappedPytorchModel
> fix model wrapper init file

- test/common_utils.py
- test/conftest.py
- test/constants.py
- test/datasets.py
- test/test_timestamp_featurizer.py
- move tests to top-level folder instead of the python folder
- add basic test infrastructure
> move tests to top-level folder

- docs/release-process.md
minor follow-up updates to release process doc based on comments in corresponding https://github.com/interpretml/interpret-community/pull/476 PR
> minor follow-up updates to release process doc based on comments

- python/ml_wrappers/version.py
- continuous integration setup
- move tests to top-level folder
- update main readme and add specification docs
- add release process doc for ml-wrappers repository
- fix issues with circular dependencies in ml-wrappers
- rename test directory to tests
- add python 3.9 tests
- add supported type check in DatasetWrapper
- separate out python linting into separate workflow
- move test_dataset_wrapper.py from test/ to tests/
- suppress tensorflow warnings that may sometimes occur on import
> release ml-wrappers v0.0.4

- python/ml_wrappers/version.py
- fix dataset wrapper to support more input types
> release ml-wrappers 0.0.5

- .github/workflows/code-scan.yml
Somehow, I missed signing one commit in PR https://github.com/microsoft/ml-wrappers/pull/25. So, I am unable to merge that. Resending the same one here.
> Add code scanning pipeline using CodeQL

- .github/workflows/CI-python.yml
- requirements-test.txt
add code coverage to ml-wrappers repository and upload the code coverage results to codecov.io
> add code coverage to ml-wrappers repository

- .github/workflows/CI-python.yml
- python/ml_wrappers/common/constants.py
- requirements-dev.txt
- tests/common_utils.py
- tests/conftest.py
- tests/test_dataset_wrapper.py
- tests/test_model_wrapper.py
Added regression and multiclass classification tests for the wrap_model function to increase code coverage.
This includes tests for scikit-learn, pytorch, xgboost and lightgbm frameworks.
> add tests for wrap_model function

- README.md
- python/ml_wrappers/dataset/dataset_wrapper.py
- python/ml_wrappers/model/model_wrapper.py
- tests/test_model_wrapper.py
- improve README documentation to showcase the dataset wrapper
- make the DatasetWrapper optional when calling the wrap_model function to simplify the API
- add basic tests for calling wrap_model without wrapping the dataset
> make DatasetWrapper optional when calling wrap_model and improve README documentation

- python/ml_wrappers/model/__init__.py
- python/ml_wrappers/model/model_wrapper.py
- python/ml_wrappers/model/pytorch_wrapper.py
- python/ml_wrappers/model/tensorflow_wrapper.py
- tests/test_model_wrapper.py
- tests/test_pytorch_model_wrapper.py
- tests/test_tf_model_wrapper.py
- tests/train_wrapper_utils.py
- tests/wrapper_validator.py
- add tensorflow model wrapper
- refactor pytorch model wrapper to a different file, but keep backwards compatibility in old namespace with import
> add tensorflow model wrapper and refactor pytorch model wrapper

- requirements-linting.txt
- tests/conftest.py
- tests/test_dataset_wrapper.py
- tests/test_model_wrapper.py
- tests/test_pytorch_model_wrapper.py
- tests/test_text_model_wrapper.py
- tests/test_tf_model_wrapper.py
- tests/test_timestamp_featurizer.py
> Add flake8-pytest-style to linting

- python/ml_wrappers/version.py
- [add tests for wrap_model function](https://github.com/microsoft/ml-wrappers/commit/30eb1ff58318d325105de567ebcd0046370bfa1a)
- [Correctly annotate python warnings](https://github.com/microsoft/ml-wrappers/commit/f6fe55b12fe5c6f781a2516dd54820cf484b2fbc)
- [Replace numpy.array with numpy.ndarray in docstrings](https://github.com/microsoft/ml-wrappers/commit/9560c72493865a0e8cc8be9499336d125ef490a8)
- [make datasetwrapper optional when calling wrap_model and improve README](https://github.com/microsoft/ml-wrappers/commit/d77ab78c9300c57b13799814feda4e7169a6d1e8)
- [add wrapper for text-based models](https://github.com/microsoft/ml-wrappers/commit/5ee6a4cf2126a098ca51bbf2b8ce8b1013c0c04a)
- [add tensorflow model wrapper and refactor pytorch model …
> release ml-wrappers v0.1.0

- python/ml_wrappers/model/text_model_wrapper.py
- tests/common_text_utils.py
- tests/test_text_model_wrapper.py
- tests/wrapper_validator.py
add a wrapper for question answering models in ml-wrappers repository so that it conforms to the predict() function specification
> add a wrapper for question answering models in ml-wrappers repository

- python/ml_wrappers/common/constants.py
- python/ml_wrappers/model/image_model_wrapper.py
- python/ml_wrappers/model/model_wrapper.py
- tests/common_vision_utils.py
- tests/test_image_model_wrapper.py
add an image model wrapper in ml-wrappers repository for image-based models
> add image model wrapper

- python/ml_wrappers/dataset/timestamp_featurizer.py
- tests/test_timestamp_featurizer.py
According to the scikit-learn guide for custom transformers here:
https://scikit-learn.org/stable/developers/develop.html
I discovered that scikit-learn expects all parameters to be attributes and also those parameters must have default values.
See related issue:
https://stackoverflow.com/questions/68925951/scikit-learn-attributeerror-in-custom-transformer
Otherwise, calling fit separately on the instantiated class does not work.
This PR fixes the CustomTimestampFeaturizer to follow these conventions and adds a test case.
> update CustomTimestampFeaturizer to conform to the scikit-learn custom transformer specifications

- python/ml_wrappers/version.py
* Update requirements-linting.txt to remove flake8-nb by @gaugup in https://github.com/microsoft/ml-wrappers/pull/45
* Update github action for checkout, upload-artifact and setup-python from version 2 to 3 by @gaugup in https://github.com/microsoft/ml-wrappers/pull/44
* add pypi prod and test release workflow github action to ml-wrappers repository by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/46
* add a wrapper for question answering models in ml-wrappers repository by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/47
* add image model wrapper by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/48
* update CustomTimestampFeaturizer to conform to the scikit-learn custom transformer specifications by @imatiach-msft in …
> release ml-wrappers v0.2.0

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Add issues templates for bugs and features for users. I just used the default templates provided by github.
> Add issues template for bugs and feature requests

- python/ml_wrappers/version.py
* fix error in ml-wrappers pypi release script by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/51
* Add issues template for bugs and feature requests by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/52
* Update requirements-dev.txt to pin transformers to less than 4.20.0 by @gaugup in https://github.com/microsoft/ml-wrappers/pull/54
* Update CI-python.yml to add python 3.10 tests by @gaugup in https://github.com/microsoft/ml-wrappers/pull/53
* add catboost framework support to ml-wrappers by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/55
**Full Changelog**: https://github.com/microsoft/ml-wrappers/compare/v0.2.0...v0.2.1
> release ml-wrappers v0.2.1

- python/ml_wrappers/version.py
* Update deprecated pypi publish github action to new supported version by @gaugup in https://github.com/microsoft/ml-wrappers/pull/58
* add wrapper for fastai image multiclass classification models by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/59
**Full Changelog**: https://github.com/microsoft/ml-wrappers/compare/v0.2.1...v0.2.2
> release ml-wrappers v0.2.2

- python/ml_wrappers/model/predictions_wrapper.py
It might be easier to process dataframes than pandas series.
> Change iteration logic from pandas series to pandas dataframe

- python/ml_wrappers/version.py
* add pytorch vision model wrapper for image classification tasks by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/69
**Full Changelog**: https://github.com/microsoft/ml-wrappers/compare/v0.3.0...v0.4.0
> release ml-wrappers v0.4.0

- python/ml_wrappers/version.py
* Automl for Images MLflow wrapper for RAI by @vadthyavath in https://github.com/microsoft/ml-wrappers/pull/73
* fix failing tests on emotion dataset by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/75
* add multilabel vision task with fastai image wrapper by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/74
**Full Changelog**: https://github.com/microsoft/ml-wrappers/compare/v0.4.0...v0.4.1
> release ml-wrappers v0.4.1

- python/ml_wrappers/model/fastai_wrapper.py
- python/ml_wrappers/model/model_wrapper.py
- tests/common_utils.py
- tests/common_vision_utils.py
- tests/main/test_model_wrapper.py
Add wrappers for fastai tabular_learner models.  Includes support for both fastai classification and regression tabular_learner models.
> add fastai tabular learner wrapper for classification and regression models

- docs/object-detection-schema.md
- python/ml_wrappers/model/image_model_wrapper.py
This PR adds documentation for the new object detection wrapper for Pytorch models.
> Comments wrapper

- python/ml_wrappers/model/__init__.py
- python/ml_wrappers/model/endpoint_wrapper.py
- requirements-dev.txt
- tests/main/test_endpoint_wrapper.py
Add a class to wrap a scoring endpoint as an MLFlow pyfunc model.
> add EndpointWrapperModel for wrapping scoring endpoints as a model

- python/ml_wrappers/version.py
* add test gate to validate ml-wrappers can be imported in an environment with minimal dependencies by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/98
* Fix typo in README.md by @ElectricalBoy in https://github.com/microsoft/ml-wrappers/pull/97
* @ElectricalBoy made their first contribution in https://github.com/microsoft/ml-wrappers/pull/97
**Full Changelog**: https://github.com/microsoft/ml-wrappers/compare/v0.4.5...v0.4.6
> release ml-wrappers 0.4.6

- python/ml_wrappers/model/image_model_wrapper.py
Without this fix, predict was failing on GPU. With this change, now we have successful dpv2 runs --
https://ml.azure.com/experiments/id/ab455878-3e59-4595-bd75-db321c20277d/runs/2bab199f-340f-4b50-94ed-359ee7ac08ef?wsid=/subscriptions/a75ae43f-9f72-4699-ba66-d3a173cfe082/resourceGroups/ilmatdpv2rg3/providers/Microsoft.MachineLearningServices/workspaces/ilmatdpv2ws3&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#
> Moving OD wrapper to device 

- python/ml_wrappers/version.py
Updating version number for ml-wrappers release with AutoML OD and DRISE support changes
> update version number to from 0.4.7 to 0.4.8

- .github/workflows/CI-python-AutoML.yml
- .github/workflows/CI-python-minimal.yml
- .github/workflows/CI-python.yml
This helps resolve the following warning:-
> Update codecov-action@v2 to codecov-action@v3

- python/ml_wrappers/model/image_model_wrapper.py
- python/ml_wrappers/model/model_wrapper.py
This PR raises the device parameter a level up to enable users to optionally control which device to run their model on.
> Cuda Configurability For ML-Wrappers

- python/ml_wrappers/version.py
* Update requirements-dev.txt to pin catboost below 1.2 by @gaugup in https://github.com/microsoft/ml-wrappers/pull/116
* Add validations for verifying the lengths of test data and prediction probabilities by @gaugup in https://github.com/microsoft/ml-wrappers/pull/115
* Update codecov-action@v2 to codecov-action@v3 by @gaugup in https://github.com/microsoft/ml-wrappers/pull/117
* return scikit-image style by default if not matched to model specific type by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/71
* Code quality for AutoML ML-Wrapper  by @natalie-isak in https://github.com/microsoft/ml-wrappers/pull/118
* Cuda Configurability For ML-Wrappers by @natalie-isak in https://github.com/microsoft/ml-wrappers/pull/120
**Full Changelog**: …
> release ml-wrappers 0.4.9

- python/ml_wrappers/model/image_model_wrapper.py
Removing excess else to improve clarity and conciseness of the code
> Style Fix In Auto Device Func

- .github/workflows/CI-python-AutoML.yml
fix build CI errors on automl pycocotools dependency install
> fix build CI errors on automl pycocotools dependency install

- .readthedocs.yaml
- python/docs/api_reference.rst
- python/docs/code_of_conduct.rst
- python/docs/conf.py
- python/docs/contributing.rst
- python/docs/dataset_wrapping.rst
- python/docs/dependencies.rst
- python/docs/getting_started.rst
- python/docs/image_model_wrapping.rst
- python/docs/index.rst
- python/docs/license_information.rst
- python/docs/model_wrapper_specifications.rst
- python/docs/model_wrapping.rst
- python/docs/object_detection_model_wrapping.rst
- python/docs/overview.rst
- python/docs/privacy_policy.rst
- python/docs/pytorch_model_wrapping.rst
- python/docs/support.rst
- python/docs/supported_frameworks.rst
- python/docs/supported_models.rst
- python/docs/tensorflow_model_wrapping.rst
- python/docs/text_model_wrapping.rst
- python/docs/versioning.rst
- requirements-doc.txt
GPT4 generated readthedocs documentation for ml-wrappers
See docs website:
https://ml-wrappers.readthedocs.io/en/latest/index.html
> generated docs for ml-wrappers

- python/ml_wrappers/model/image_model_wrapper.py
- python/ml_wrappers/model/text_model_wrapper.py
- python/ml_wrappers/model/wrapped_classification_model.py
Add conversion to np.array to text/vision wrappers predict method
> convert predict result to numpy array

- python/ml_wrappers/version.py
Releasing new version with the `predict_proba` fix to unblock https://github.com/microsoft/responsible-ai-toolbox/pull/2203
> Release new version of ml-wrappers

- python/ml_wrappers/version.py
* modify automl threshold params and add gpu optimizations in object detection ml-wrappers by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/144
**Full Changelog**: https://github.com/microsoft/ml-wrappers/compare/v0.4.13...v0.5.0
> release ml-wrappers 0.5.0

- python/ml_wrappers/version.py
* add default case for object detection to pass through models that have already been wrapped correctly by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/150
* Update requirements-linting.txt to add flake8-all-not-strings by @gaugup in https://github.com/microsoft/ml-wrappers/pull/149
* ml-wrappers: Remove flake8 pins by @gaugup in https://github.com/microsoft/ml-wrappers/pull/151
**Full Changelog**: https://github.com/microsoft/ml-wrappers/compare/v0.5.1...v0.5.2
> release ml-wrappers 0.5.2

- python/ml_wrappers/version.py
* Update README.md to add status badges by @gaugup in https://github.com/microsoft/ml-wrappers/pull/154
* add optional api key auto refresh callable to EndpointWrapperModel by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/153
* Update CI-python.yml to remove python 3.6 logic by @gaugup in https://github.com/microsoft/ml-wrappers/pull/157
* Add python 3.11 builds to CI-python-minimal.yml by @gaugup in https://github.com/microsoft/ml-wrappers/pull/155
* fix wrapper error for object detection models on empty model predictions by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/158
* update openai wrapper model to support new openai 1.0 APIs by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/160
* Fix for empty predictions by @Advitya17 in …
> release ml-wrappers 0.5.3

- .github/workflows/CI-python-AutoML.yml
- .github/workflows/CI-python-minimal.yml
- .github/workflows/CI-python.yml
- .github/workflows/code-scan.yml
- .github/workflows/linkcheck.yml
- .github/workflows/python-linting.yml
- .github/workflows/release-ml-wrappers.yml
- Updating setup-miniconda from 2 to 3
- Update checkout from 3 to 4
> Update versions for github actions

- python/ml_wrappers/version.py
* Update versions for github actions by @gaugup in https://github.com/microsoft/ml-wrappers/pull/161
* Upgrade setup-python from v4 to v5 by @gaugup in https://github.com/microsoft/ml-wrappers/pull/162
* fix openai wrapper compatibility with older version of openai less than 1.0.0 by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/163
**Full Changelog**: https://github.com/microsoft/ml-wrappers/compare/v0.5.3...v0.5.4
> release ml-wrappers 0.5.4

- python/ml_wrappers/model/predictions_wrapper.py
When a single row is found, then we can stop the search earlier. This helps bring down the run time when the number of features is large.
> PredictionWrapper: Stop search earlier when the candidate is found

- python/ml_wrappers/version.py
* Update default python build to 3.9 and add 3.11, fix build failures by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/179
* Update numpy and pandas to >2.0 in ml-wrappers by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/180
* Update upload-artifact to v4 and fix release script in ml-wrappers by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/182
**Full Changelog**: https://github.com/microsoft/ml-wrappers/compare/v0.5.6...v0.6.0
> release ml-wrappers 0.6.0
