microsoft/ml-wrappers

python/ml_wrappers/common/gpu_kmeans.py, python/ml_wrappers/dataset/dataset_utils.py, python/ml_wrappers/dataset/dataset_wrapper.py
fix circular dependency errors in ml-wrappers due to imports from interpret-community
Note:
_generate_augmented_data and _summarize_data are now moved inside ml-wrappers, including gpu_kmeans code which used to be in interpret-community
=> fix issues with circular dependencies in ml-wrappers (dependencies on interpret-community)

.gitignore
this PR updates the gitignore file to use the python specific ignore settings from https://github.com/github/gitignore repo, specifically concatenating the file:
https://github.com/github/gitignore/blob/main/Python.gitignore
=> update gitignore file for python

python/ml_wrappers/model/__init__.py
a downstream package has issues because it reimported these from interpret-community, which did not reimport them from ml-wrappers
=> fix imports in model init file to include WrappedClassificationModel and WrappedRegressionModel

README.md, python/ml_wrappers/dataset/dataset_utils.py, python/ml_wrappers/dataset/dataset_wrapper.py, tests/common_utils.py, tests/test_dataset_wrapper.py, tests/test_model_wrapper.py
Add support for tensorflow BatchDataset to DatasetWrapper.
The BatchDataset is converted to internal numpy format for processing.
Resolves user issue:
https://github.com/interpretml/interpret-community/issues/503
Also, adds more thorough roundtrip tests for the various types supported by DatasetWrapper, and adds a test for wrapping a tensorflow model that operates on a BatchDataset.
=> add support for tensorflow BatchDataset to DatasetWrapper

requirements-linting.txt
It seems the linting building is broken to due a breaking change in nbconvert which is because of importing from flake8-nb.
```
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/flake[8](https://github.com/microsoft/ml-wrappers/runs/5880733704?check_suite_focus=true#step:6:8)/plugins/manager.py", line 157, in load_plugin
self._load()
File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line 134, in _load
self._plugin = self.entry_point.load()
File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 203, in load
module = import_module(match.group('module'))
File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/importlib/__init__ …
```
=> Update requirements-linting.txt to remove flake8-nb

.github/workflows/release-ml-wrappers.yml
Fix error in name field of pypi release script:
Error: Artifact name is not valid: ./python. Contains the following character:  Forward slash /
Update:
link to passing upload to pypi test: https://github.com/microsoft/ml-wrappers/actions/runs/2470763658
=> fix error in ml-wrappers pypi release script

requirements-dev.txt
It seems like the recent with the recent release of transformers (4.20.X) the test `test_wrap_transformers_model` is broken with the following stack trace:-
```
=================================== FAILURES ===================================
______________ TestTextModelWrapper.test_wrap_transformers_model _______________
self = <test_text_model_wrapper.TestTextModelWrapper object at 0x7fd8a8535060>
def test_wrap_transformers_model(self):
emotion_data = load_emotion_dataset()
docs = emotion_data[:10].drop(columns=EMOTION).values.tolist()
pred = create_text_classification_pipeline()
wrapped_model = wrap_model(pred, docs, ModelTask.TEXT_CLASSIFICATION)
>       validate_wrapped_classification_model(wrapped_model, docs)
/home/runner/work/ml-wrappers/ml-wrappers/tests/test_text_model_wrapper.py: …
```
=> Update requirements-dev.txt to pin transformers to less than 4.20.0

docs/WrapperSpecifications.md, python/ml_wrappers/model/function_wrapper.py, python/ml_wrappers/model/model_wrapper.py, requirements-dev.txt, tests/common_utils.py, tests/test_model_wrapper.py
Resolves issue:
https://github.com/microsoft/responsible-ai-toolbox/issues/1590
Currently catboost classifier and regressor are not supported by ml-wrappers.  This PR adds support for catboost framework.  Mainly, the current predict and predict_proba functions from catboost classifier fail to support scikit-learn specification due to two issues:
1.) Catboost predict_proba returns different results when either a single array is passed to the prediction function or multiple arrays are passed.  In the single instance case, catboost returns a single dimensional array of probabilities, whereas scikit-learn models always return a two-dimensional array of probabilities.
2.) Catboost predict function returns two dimensional array of one column, in the format [[1], [3], [2], [1]] etc, whereas …
=> add catboost framework support to ml-wrappers

.github/workflows/CI-python.yml
Currently the gated build is failing on macos due to a lower numpy reinstall from pip (when package is already installed from conda).  I'm not sure which dependency this limit is coming from, pandas or scikit-learn, but it occurs during the editable install of ml-wrappers.  When re-installing numpy from pip, the incompatibilities cause unstable behavior which results in seg-fault errors when running tests in macos.
Note we don't use the bound for python 3.6, as it seems it then installs a too-new version of numpy, which causes an ancient version of pytorch to be installed for some reason.
=> prevent build error via lower numpy version from conda to prevent re-install from pip

.github/workflows/release-ml-wrappers.yml
Changing the github action from master to release based on the PR https://github.com/microsoft/responsible-ai-toolbox/pull/1595/files.
=> Update deprecated pypi publish github action to new supported version

python/ml_wrappers/model/image_model_wrapper.py, requirements-dev.txt, tests/common_vision_utils.py, tests/test_image_model_wrapper.py
Add a wrapper to support fastai vision learner models for multiclass classification.
Also adds a test case on a custom model for the image fridge classification dataset created at Microsoft Cambridge.
=> add wrapper for fastai image multiclass classification models

.github/workflows/CI-python.yml, .github/workflows/code-scan.yml, .github/workflows/python-linting.yml
Since there are not many PRs daily in this repo, we wouldn't know when one of the PR gates would start failing. Hence scheduling a build everyday to run at 5:30am UTC.
=> Add scheduled builds for github workflows in ml-wrappers

requirements-linting.txt
The scheduled linting build failed with the following error trace:-
```
Run flake8 . --max-line-length=119 --count --max-complexity=20 --exclude=.git/,__pycache__/,dist/ --show-source --statistics
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.[7](https://github.com/microsoft/ml-wrappers/actions/runs/3174913342/jobs/5172303293#step:6:8).14/x64/bin/flake[8](https://github.com/microsoft/ml-wrappers/actions/runs/3174913342/jobs/5172303293#step:6:9)", line 8, in <module>
sys.exit(main())
File "/opt/hostedtoolcache/Python/3.7.[14](https://github.com/microsoft/ml-wrappers/actions/runs/3174913342/jobs/5172303293#step:6:15)/x64/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
app.run(argv)
File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-pack …
```
=> Update flake8 to 4.0.1 in requirements-linting.txt to fix flake8 gate

python/ml_wrappers/model/predictions_wrapper.py, tests/test_predictions_wrapper.py
The model wrapper base class `ModelWrapperPredictions` wraps the test data and model prediction and supports the predict call. The `ModelWrapperPredictionsClassification` also supports the `predict_proba` method.
=> Add model wrapper for wrapping data and predictions

tests/common_utils.py, tests/test_predictions_wrapper.py
Adding a unit test to cover the scenario when there can be string features in the dataset.
=> Add titanic dataset to prediction model wrapper tests

python/ml_wrappers/common/constants.py, python/ml_wrappers/model/model_utils.py, python/ml_wrappers/model/text_model_wrapper.py, tests/common_text_utils.py, tests/test_text_model_wrapper.py, tests/wrapper_validator.py
Add wrapper for multilabel huggingface models in wrap_model method.
Given the scikit-learn docs here:
https://scikit-learn.org/stable/modules/multiclass.html?highlight=multilabel#multilabel-classification
The common wrapper will follow the format of the multioutput classifier:
https://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputClassifier.html#sklearn.multioutput.MultiOutputClassifier.predict
This format is a two-dimensional indicator array by num rows X num labels, where for index i = 1 if the corresponding label is output by the model:
https://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputClassifier.html#sklearn.multioutput.MultiOutputClassifier.predict
=> add multilabel text model wrapper

tests/common_text_utils.py, tests/common_utils.py
There seems to be a known issue with emotion dataset on huggingface failing to download, see:
https://github.com/dair-ai/emotion_dataset/issues/5
The dataset is hosted externally,
Using an alternative link to the dataset on huggingface which is hosted internally.
Update: Also remove normalize parameter as it has been removed on latest scikit-learn pypi package's LinearRegression class to unblock failing builds.
=> fix failing tests on emotion dataset

python/ml_wrappers/common/constants.py, python/ml_wrappers/model/image_model_wrapper.py, tests/common_vision_utils.py, tests/main/test_image_model_wrapper.py
Add support for the multilabel image classification task to ml-wrappers.  Includes adding support for fastai multilabel image classification models and a test on the multilabel fridge classification dataset with a fine-tuned fastai model.
=> add multilabel vision task with fastai image wrapper

.github/workflows/release-ml-wrappers.yml
Hotfix for release build failing:
https://github.com/microsoft/ml-wrappers/actions/runs/3659856132
The release build includes the full tests folder which runs the AutoML tests.  However, the newly added AutoML tests don't have dependencies installed in the release build.  This PR changes the command to only run the main tests in the main folder and excludes the AutoML tests, which are run on gated builds anyway already.
=> fix failing ml-wrappers release build due to automl tests being included without dependencies installed

python/ml_wrappers/model/image_model_wrapper.py, requirements-dev.txt
hotfix to ml-wrappers to make mlflow PyFuncModel import optional (no hard dependency) which is causing upstream errors
mlflow is getting automatically imported and failing in many environments where it is not needed and is not installed.
This is caused by the import added in the recent PR https://github.com/microsoft/ml-wrappers/pull/73 .
The fix here is to take a soft dependency on the import.
=> hotfix to ml-wrappers to make mlflow PyFuncModel import optional (no hard dependency) which is causing upstream errors

python/ml_wrappers/version.py
* hotfix to ml-wrappers to make mlflow PyFuncModel import optional (no hard dependency) which is causing upstream errors by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/79
**Full Changelog**: https://github.com/microsoft/ml-wrappers/compare/v0.4.1...v0.4.2
=> release ml-wrappers 0.4.2

python/README.md, python/setup.py
It looks like we have tests for python 3.10 but we don't show it in setup.py or the docs.
=> Add python 3.10 to setup.py and docs

README.md, SECURITY.md, SUPPORT.md
Remove dead links causing build failures in ml-wrappers repository in the new "Link check" github action.
=> remove dead links in support page

python/ml_wrappers/model/fastai_wrapper.py, tests/common_utils.py, tests/main/test_model_wrapper.py, tests/train_wrapper_utils.py
During customer debugging there were several issues discovered with the fastai model wrapper:
1.) Sometimes the predict call can evaluate some metrics if true label is included, and those metrics can fail when run on a single row.  The simple fix is to ensure that only the relevant feature columns are passed to the predict method call.
2.) Fastai has a complex system of callbacks and these can sometimes fail.  In case the predict call fails due to callbacks, this PR removes all but the most common system callbacks to ensure predict can still pass.
=> fix fastai get_preds on inference when callbacks failing

.github/workflows/CI-python.yml, tests/main/test_image_model_wrapper.py
Disabling MAC OS tests temporarily because of various seg faults seen due to pytorch dependencies.
=> Disabling MAC OS tests due to seg fault failures

.github/workflows/CI-python.yml, tests/main/test_image_model_wrapper.py, tests/main/test_model_wrapper.py
The gated builds were failing with a segfault which was fixed when updating pytorch to use latest version by including conda-forge channel during conda install.  When not installing with conda-forge channel included we were actually installing an older version of pytorch.
However, some fastai tests then started to fail with the error:
```
>       return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
E       RuntimeError: Exception occured in `TrainEvalCallback` when calling event `before_fit`:
E       	The MPS backend is supported on MacOS 12.3+.Current OS version can be queried using `sw_vers`
```
It seems that fastai support for macos is sparse based on their readme documentation and issues:
https://github.com/fastai/fastai/
For example, on their …
=> re-enable macos python tests in gated builds

.github/workflows/CI-python-AutoML.yml, .github/workflows/CI-python.yml
Build failures seem to be happening frequently on codecov upload logic.  This PR attempts to fix these by making the logic more similar to https://github.com/microsoft/vision-explanation-methods/blob/main/.github/workflows/CI-python.yml and https://github.com/microsoft/responsible-ai-toolbox/blob/main/.github/workflows/CI-python.yml.  Specifically, we:
1.) only upload to codecov once, for a specific python environment + OS combination
2.) add retry logic, to retry codecov upload again if it failed
In the other repositories mentioned above this has resolved the codecov upload issue and hence it's expected to resolve the issue in the build + test script in this ml-wrappers repository too.
=> reduce codecov uploads and add retry logic to fix frequent random build failures

.github/workflows/CI-python.yml
This PR fixes build errors that started occurring on the windows platform with libtiff 4.5.0 update.
The runtime test errors are:
```
C:\Miniconda\envs\test\lib\site-packages\transformers\utils\import_utils.py:874: in _get_module
raise RuntimeError(
E   RuntimeError: Failed to import transformers.models.auto because of the following error (look up to see its traceback):
E   Failed to import transformers.onnx.config because of the following error (look up to see its traceback):
E   DLL load failed while importing _imaging: The specified module could not be found.
```
=> fix Pillow build error from libtiff 4.5.0

python/ml_wrappers/version.py
* hotfix for ml-wrappers import for GeneralObjectDetectionModelWrapper when vision-explanation-methods package not installed by @imatiach-msft in https://github.com/microsoft/ml-wrappers/pull/95
**Full Changelog**: https://github.com/microsoft/ml-wrappers/compare/v0.4.4...v0.4.5
=> release ml-wrappers 0.4.5

.github/workflows/CI-python-minimal.yml, python/ml_wrappers/model/image_model_wrapper.py, tests/conftest.py, tests/minimal/test_minimal.py
After the release which broke downstream applications which led to the hotfix:
https://github.com/microsoft/ml-wrappers/pull/95
We realized we should add some additional test coverage to validate ml-wrappers can be imported in a "minimal" environment where only the most basic dependencies in the setup.py file are specified.  This PR adds this gate and some basic import tests.  We could add more validation logic as well in the future (eg calling wrap_model on a simple scikit-learn model in this minimal environment).
This PR also fixes another issue where Torch is imported and used in the code which will also fail if pytorch is not installed.  The new build/test gate actually caught this issue.
=> add test gate to validate ml-wrappers can be imported in an environment with minimal dependencies

python/ml_wrappers/model/image_model_wrapper.py
Making all thresholds consistent b/w drise and generic object detection wrappers. There were bugs without this fix in that not all detections were captured by the saliency maps.
=> Consistent Thresholds B/w Diff O.D Wrappers

python/ml_wrappers/model/image_model_wrapper.py, python/ml_wrappers/version.py
This PR updates the version number to release the following changes: https://github.com/microsoft/ml-wrappers/pull/102.
To summarize, this fixes a bug in which the iou thresholds were not the same between two object detection wrappers.
=> Version Update (IOU threshold bug fix)

python/ml_wrappers/model/predictions_wrapper.py
Looks like using `iteritems()` will be deprecated in pandas 2.0.0. So using `items()` instead.
=> Update predictions_wrapper.py to change from iteritems() to items()

.github/workflows/python-linting.yml
Looks like python 3.7 will be deprecated in June 2023. So updating the python to 3.10 in linting workflow.
=> Update python-linting.yml to use python 3.10

requirements-dev.txt
There was a release on May 1st which seems to have broken the build on MAC OS. Hence, pinning catboost to below 1.2.
=> Update requirements-dev.txt to pin catboost below 1.2

python/ml_wrappers/model/image_model_wrapper.py, python/ml_wrappers/model/model_utils.py, tests/common_vision_utils.py, tests/main/test_image_model_wrapper.py
When given a scikit-learn style model with predict and predict_proba functions for the image classification task, we were previously wrapping it by default with the transformers wrapper.  This doesn't make sense, and causes issues for such types of models.  This PR updates the image classification wrapping logic to just return the scikit-learn style models by default for image classification case.
=> return scikit-image style by default if not matched to model specific type

python/ml_wrappers/model/image_model_wrapper.py, tests/automl/test_automl_image_object_detection_model_wrapper.py, tests/main/test_image_model_wrapper.py
Improving code quality of object detection scenario of ml-wrappers.
Adding a check for the type of classes. There is some confusion regarding the input of the classes variable, so this check ensures that classes is a list of strings representing classes. If not, a clear exception is thrown. 
According unit tests added. 
For ref - https://msdata.visualstudio.com/Vienna/_backlogs/backlog/Responsible%20AI/Epics/?workitem=2355376
=> Code quality for AutoML ML-Wrapper 

python/setup.py, requirements-dev.txt
Similar failure seen as in PR https://github.com/microsoft/responsible-ai-toolbox/pull/2155. So fixing this by pinning joblib in requirement-dev.txt.
=> Pin joblib to below 1.3.0 to fix build gates

.github/workflows/release-ml-wrappers.yml
Update the python version to 3.8 in release workflows. Python 3.7 has reached end of life. Updating to 3.8.
=> Update the python version to 3.8 in release workflows

python/ml_wrappers/model/function_wrapper.py, requirements-dev.txt, tests/common_utils.py
The latest tensorflow release has dropped KerasClassifier and KerasRegressor scikit-learn style wrappers.  This has caused all of our gated builds to fail in our ml-wrappers repository on all PRs.  See commit in tensorflow that dropped them:
https://github.com/tensorflow/tensorflow/commit/f08737e6420fbc53f0ab2e299bee725a04499ba8
based on the issue in tensorflow:
https://github.com/tensorflow/tensorflow/issues/32532
```
It seems that the KerasRegressor and Kerasclassifier is deprecated and we are no longer maintaining/bug fixing it. Please forward this issue to https://github.com/adriangb/scikeras.
```
It seems it is recommended to move to the scikeras package instead.
Hence, this PR adds a dependency to scikeras and uses the KerasClassifier and KerasRegressor from scikeras instead for …
=> migrate tests to KerasClassifier and KerasRegressor from scikeras since tensorflow has removed them to fix builds

python/ml_wrappers/model/predictions_wrapper.py, tests/main/test_predictions_wrapper.py
The pandas `query()` function is slow to find records with specific values. More on efficiently searching the pandas dataframe at [link](https://docs.kanaries.net/tutorials/Pandas/pandas-search-value-column).
The proposed solution is to use `iloc()` function is pandas. The time taken using `iloc()` is better than pandas `query()` function.
| Rows | Search time using query() (sec) | Search time using iloc() (sec) |
|----------|----------|----------|
| 10   | 0.46  | 0.46 |
| 100   | 1.98  | 1.43  |
| 200   |3.73  | 1.77  |
| 300   | 4.54  | 2.50  |
| 400   | 5.71  | 2.65  |
| 500   | 4.51  | 2.78 |
| 1000   | 9.20  | 5.70  |
| 2000   | 26.63 |13.39  |
| 3000   | 35.02  | 16.93 |
| 4000   | 43.87  | 22.60  |
| 5000   | 43.94  | 28.84  |
=> Improve run time performance of prediction wrappers

python/ml_wrappers/model/__init__.py, python/ml_wrappers/model/openai_wrapper.py, requirements-dev.txt, tests/main/test_openai_wrapper.py
Add openai model endpoint wrapper.  This includes the wrapper around an azure openai API, the retry logic to attempt calling the API multiple times incase of network flakiness, and logic to re-wrap the model's output as a pandas dataframe.
=> add openai model endpoint wrapper

python/ml_wrappers/model/tensorflow_wrapper.py, tests/main/test_tf_model_wrapper.py
The Sequential layer class namespace changed in the latest tensorflow 2.13 to keras.src.engine.sequential.Sequential from the previous keras.engine.sequential.Sequential namespace.
This caused test failures in interpret-community repository for the PFI explainer:
https://github.com/interpretml/interpret-community/commit/e4e75f901a56e625811be44883492c16945d3269#diff-82a69909fb9f2e27dcff4f01ede5603b921c76d22635167fe321f73c990c8e10
The test there has been temporarily disabled for now.
This PR fixes the issue for all tensorflow versions and adds a test case.
=> fix is_sequential check for latest tensorflow 2.13

.github/workflows/CI-python-minimal.yml, .github/workflows/CI-python.yml, python/README.md, python/setup.py, tests/common_utils.py
Changing this to `sparse_output` instead. More in documentation here:- https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html.
Also removing tests and documentation for python 3.6 and 3.7 as these versions of python are end of life.
=> Remove deprecated parameter `sparse` from `OneHotEncoder`

python/ml_wrappers/model/predictions_wrapper.py, tests/main/test_predictions_wrapper.py
The prediction wrappers fail if there is missing data in the dataset. This PR handles the missing values while doing predict/predict_proba is prediction wrappers.
=> Handle missing values in predictions wrapper

python/docs/object_detection_model_wrapping.rst, python/ml_wrappers/model/image_model_wrapper.py, tests/automl/test_automl_image_object_detection_model_wrapper.py, tests/main/test_image_model_wrapper.py
modify automl threshold params and add gpu optimizations in object detection ml-wrappers
1.) fix _get_device to be able to handle colons with device number
2.) add transforms to PytorchDRiseWrapper for AutoML support via extracting underlying model as an optimization for running AutoML models on GPU
3.) add threshold params for iou_thresh and score_thresh to predict method and also allow them to be specified on constructor
4.) rename score_thresh and iou_thresh to full name score_threshold and iou_threshold, since we have many cases where these seem to be inconsistent in the codebase - note it looks like these are not used elsewhere in our codebases so it should not affect other projects, but it is a breaking change in case other external users are calling these APIs directly
5.) add …
=> modify automl threshold params and add gpu optimizations in object detection ml-wrappers

python/ml_wrappers/model/image_model_wrapper.py
The `detections` list was converted to np.array in https://github.com/microsoft/ml-wrappers/pull/139 due to the below error:
Bug 2532332 RangeIndex Error when users bring their own model with text and vision
However, conversion to np.array may not usually be technically possible as there can be variable number of detections per image which may not make the 3D list a defined-sized matrix, for example:
Example error - https://github.com/microsoft/responsible-ai-toolbox/actions/runs/5906085087/job/16021413911?pr=2246
Hence this PR tries converting to np.array if possible to stay compatible with the return type of the rest of the wrappers, else returns the plain list with variable number of detections per image.
=> Updated return type logic for OD detections

python/ml_wrappers/model/image_model_wrapper.py, tests/main/test_image_model_wrapper.py
Currently object detection models that have been wrapped are always getting re-wrapped as a WrappedObjectDetectionModel.  However, this can cause issues for users that have already written their own custom wrapper, as is the case for one of our customers.  In the image model wrapper, we simply return the existing model if we detect that it has already been wrapped, similar to other text and tabular wrappers as well as vision wrappers for other tasks.
=> add default case for object detection to pass through models that have already been wrapped correctly

python/ml_wrappers/model/endpoint_wrapper.py, tests/main/test_endpoint_wrapper.py
Add an optional api key auto refresh callable to EndpointWrapperModel to allow the api key to be refreshed automatically.
Also adds a test.
This additional parameter/constructor was added due to errors users have encountered with the notebook:
https://github.com/Azure/azureml-examples/blob/main/sdk/python/responsible-ai/text/responsibleaidashboard-text-classification-blbooksgenre.ipynb
Specifically, after a day the api key expires, and users start to see errors like:
```
Jwt is expired
Please check this guide to understand why this error code might have been returned 
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-troubleshoot-online-endpoints#http-status-codes
Failed to convert result to numpy array, json_data:
Traceback (most recent call last):
File …
```
=> add optional api key auto refresh callable to EndpointWrapperModel

.github/workflows/CI-python.yml
Looks like python 3.6 is no longer part of the text matrix. So the logic specific to python 3.6 can be removed.
=> Update CI-python.yml to remove python 3.6 logic

python/ml_wrappers/model/image_model_wrapper.py, tests/main/test_image_model_wrapper.py
Fix for below issue:
<class 'RuntimeError'> File "/azureml-envs/responsibleai-vision/lib/python3.8/site-packages/azureml/rai/utils/telemetry/loggerfactory.py", line 153 in wrapper return func(*args, **kwargs) File "./rai_vision_insights.py", line 456 in main rai_vi = RAIVisionInsights( File "/azureml-envs/responsibleai-vision/lib/python3.8/site-packages/responsibleai_vision/rai_vision_insights/rai_vision_insights.py", line 254 in __init__ self._initialize_managers() File "/azureml-envs/responsibleai-vision/lib/python3.8/site-packages/responsibleai_vision/rai_vision_insights/rai_vision_insights.py", line 271 in _initialize_managers self._error_analysis_manager = ErrorAnalysisManager( File "/azureml-envs/responsibleai-vision/lib/python3.8/site-packages/responsibleai_vision/managers/error_ana …
=> Fix for empty predictions

.github/workflows/CI-python.yml, python/ml_wrappers/model/openai_wrapper.py, tests/main/test_openai_wrapper.py
Customer encountered exception when using openai<1.0.0 with OpenaiWrapperModel from ml-wrappers:
Fixing error and adding test case with old version of openai in test matrix to validate.
=> fix openai wrapper compatibility with older version of openai less than 1.0.0

python/ml_wrappers/model/openai_wrapper.py, tests/main/test_openai_wrapper.py
The current implementation checks if the `ChatCompletion` attribute exists in the `openai` package and calls it if it does.
The newer versions of the `openai` package have this attribute but they are programmed to show an error message saying the user is trying to access a symbol that is no longer supported. So, the `hasattr` check passes but the call to `ChatCompletion` then fails.
This check is now replaced with `self.client is None` which is true for `openai<1.0.0` and false for `openai>=1.0.0`, so the correct method is called for all versions.
=> Fix openai version check

python/ml_wrappers/model/openai_wrapper.py, tests/main/test_openai_wrapper.py
Currently, when calling the `.predict()` method of the openai wrapper with a `dict` or `pandas.DataFrame`, the method looks for the `"questions"` key/column in the input to get the prompts that need to be sent to the OpenAI API to make the predictions.
The default behavior has now been changed to look for `"prompt"` key/column in the input, and falling back to the `"questions"` column if not found to maintain backwards compatibility. Additionally, the users can now also specify a different column name of their choice by specifiying the `input_col` keyword-argument when initializing the wrapper model.
```python
from ml_wrappers.model import OpenaiWrapperModel
model = OpenaiWrapperModel(
API_TYPE,
API_BASE,
API_VERSION,
API_KEY,
input_col='my_input_col')
```
=> make input column customizable for openai wrapper

.github/workflows/CI-python-AutoML.yml, .github/workflows/CI-python-minimal.yml, .github/workflows/CI-python.yml, python/docs/dependencies.rst, python/ml_wrappers/dataset/dataset_wrapper.py, python/setup.py, requirements-automl.txt, requirements-dev.txt, tests/automl/test_automl_image_model_wrapper.py, tests/automl/test_automl_image_object_detection_model_wrapper.py, tests/common_utils.py, tests/common_vision_utils.py, tests/main/test_model_wrapper.py, tests/main/test_text_model_wrapper.py, tests/main/test_tf_model_wrapper.py
fix build failures and also update to scikit-learn OneHotEncoder sparse parameter to sparse_output for newer scikit-learn versions
Contains several updates to latest azureml automl package, updates to use python 3.9 as default env in tests, and various updates to newer packages to resolve test failures.
Copilot summary:
This pull request includes various updates to the CI workflows, dependencies, and test configurations to improve compatibility and functionality. The most important changes focus on updating Python and package versions, modifying CI workflows, and addressing compatibility issues in the codebase.
* [`.github/workflows/CI-python-AutoML.yml`](diffhunk://#diff-ac99add371ffd03527acbe4b88283ab0be579c27163c5c71a6bacc559980620aL16-R17): Limited `operatingSystem` to `ubuntu-latest` …
=> fix build failures and also update to scikit-learn OneHotEncoder sparse parameter to sparse_output for newer scikit-learn versions

python/ml_wrappers/dataset/dataset_wrapper.py, python/ml_wrappers/model/tensorflow_wrapper.py, python/ml_wrappers/version.py, tests/main/test_model_wrapper.py, tests/main/test_tf_model_wrapper.py
This PR is mainly to fix one of our nightly notebook tests that is failing.  In the notebook test we are using the EndpointWrapper from ml-wrappers but getting the error for the file https://github.com/Azure/azureml-examples/blob/main/sdk/python/responsible-ai/text/responsibleaidashboard-text-classification-blbooksgenre.ipynb:
```
2024-08-19T18:56:24.3991935Z     615 def __new__(cls, name, full_name, index, number, type, cpp_type, label,
2024-08-19T18:56:24.3992539Z     616             default_value, message_type, enum_type, containing_type,
2024-08-19T18:56:24.3993063Z     617             is_extension, extension_scope, options=None,
2024-08-19T18:56:24.3993504Z     618             serialized_options=None,
2024-08-19T18:56:24.3993993Z     619             has_default_value=True, …
```
=> Fix tensorflow import in dataset wrapper to handle invalid tensorflow installation due to unsupported protobuf

python/docs/dependencies.rst, python/setup.py, tests/common_vision_utils.py
Update numpy and pandas >2.0 in ml-wrappers, including test fixes due to deprecation of append API in pandas
Resolves issue https://github.com/microsoft/ml-wrappers/issues/178
=> Update numpy and pandas to >2.0 in ml-wrappers
